-- MySQL Script generated by MySQL Workbench
-- 08/06/18 14:01:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CountriesAndCitiesOfTheWorld
-- -----------------------------------------------------
-- Страны и города мира

-- -----------------------------------------------------
-- Schema CountriesAndCitiesOfTheWorld
--
-- Страны и города мира
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CountriesAndCitiesOfTheWorld` DEFAULT CHARACTER SET utf8 ;
USE `CountriesAndCitiesOfTheWorld` ;

-- -----------------------------------------------------
-- Table `CountriesAndCitiesOfTheWorld`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CountriesAndCitiesOfTheWorld`.`Countries` (
  `Primary_key` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Primary_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CountriesAndCitiesOfTheWorld`.`Regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CountriesAndCitiesOfTheWorld`.`Regions` (
  `Primary_key` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  `Country_id` INT NOT NULL,
  PRIMARY KEY (`Primary_key`),
  INDEX `KeyCountry_idx` (`Country_id` ASC),
  CONSTRAINT `KeyCountry`
    FOREIGN KEY (`Country_id`)
    REFERENCES `CountriesAndCitiesOfTheWorld`.`Countries` (`Primary_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CountriesAndCitiesOfTheWorld`.`Districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CountriesAndCitiesOfTheWorld`.`Districts` (
  `Primary_key` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Primary_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CountriesAndCitiesOfTheWorld`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CountriesAndCitiesOfTheWorld`.`Cities` (
  `Primary_key` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  `Region_id` INT NOT NULL,
  `District_id` INT NULL,
  PRIMARY KEY (`Primary_key`),
  INDEX `KeyDistrict_idx` (`District_id` ASC),
  INDEX `KeyRegion_idx` (`Region_id` ASC),
  CONSTRAINT `KeyDistrict`
    FOREIGN KEY (`District_id`)
    REFERENCES `CountriesAndCitiesOfTheWorld`.`Districts` (`Primary_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `KeyRegion`
    FOREIGN KEY (`Region_id`)
    REFERENCES `CountriesAndCitiesOfTheWorld`.`Regions` (`Primary_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CountriesAndCitiesOfTheWorld`.`Countries`
-- -----------------------------------------------------
START TRANSACTION;
USE `CountriesAndCitiesOfTheWorld`;
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Countries` (`Primary_key`, `Name`) VALUES (1, 'France');
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Countries` (`Primary_key`, `Name`) VALUES (2, 'Germany');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CountriesAndCitiesOfTheWorld`.`Regions`
-- -----------------------------------------------------
START TRANSACTION;
USE `CountriesAndCitiesOfTheWorld`;
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Regions` (`Primary_key`, `Name`, `Country_id`) VALUES (1, 'Brittany', 1);
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Regions` (`Primary_key`, `Name`, `Country_id`) VALUES (2, 'Centre-Val de Loire', 1);
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Regions` (`Primary_key`, `Name`, `Country_id`) VALUES (3, 'Baden-Württemberg', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CountriesAndCitiesOfTheWorld`.`Districts`
-- -----------------------------------------------------
START TRANSACTION;
USE `CountriesAndCitiesOfTheWorld`;
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Districts` (`Primary_key`, `Name`) VALUES (1, 'Ille-et-Vilaine');
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Districts` (`Primary_key`, `Name`) VALUES (2, 'Finistère');
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Districts` (`Primary_key`, `Name`) VALUES (3, 'Alb-Donau');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CountriesAndCitiesOfTheWorld`.`Cities`
-- -----------------------------------------------------
START TRANSACTION;
USE `CountriesAndCitiesOfTheWorld`;
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Cities` (`Primary_key`, `Name`, `Region_id`, `District_id`) VALUES (1, 'Rennes', 1, 1);
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Cities` (`Primary_key`, `Name`, `Region_id`, `District_id`) VALUES (2, 'Brest', 1, 2);
INSERT INTO `CountriesAndCitiesOfTheWorld`.`Cities` (`Primary_key`, `Name`, `Region_id`, `District_id`) VALUES (3, 'Langenau', 3, NULL);

COMMIT;

