require 'rubygems'
require 'bundler/setup'

def scan(path, counter = 0)
  entries = Dir.new(path).reject { |x| %w[. ..].include? x }
  entries.map! { |x| path.join x }
  entries.reduce(counter) do |count, item|
    if File.directory? item
      scan(item, count)
    elsif item.extname == '.rb'
      count + 1
    else count
    end
  end
end

desc 'Возвращает кол-во Ruby-файлов в указанной папке и всех вложенных'
task :scan, [:path] do |_t, arg| # >rake scan['c:/Projects/Geekbrains/Ruby']
  path = Pathname.new(arg[:path])
  puts scan(path) # 81
end
