# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rake'
gem 'ruby-progressbar'
# gem 'hello', path: 'hello'

# group :development, :test do
#   gem 'rspec','3.7.0', require: false
# end
