require 'open-uri'

task default: :load 

namespace :docs do
  desc 'Загружает страницу класса с ruby-doc.org'
  task :load, [:klasses] do |_t, arg|
    name = arg[:klasses]
    ext = arg.extras
    ext.insert(0, name)
    ext.compact.each do  |klass|
        url = format('https://ruby-doc.org/core-2.4.2/%s.html',klass)
        File.write("#{klass}.txt",open(url).read)
    end
    # rubypage = open('https://ruby-doc.org/core-2.4.2/String.html')
    # puts rubypage.read
  end
end